sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTAI5tD8CiVaASkHf7Jjnhoz
    access-key-secret: yEP3XhvfkNzgXZ2cmkl8FbdrZN6Ojl
    bucket-name: sky-take-out599
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10